# permissions for end users to view annotationwatchlists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotationwatchlist-viewer-role
rules:
- apiGroups:
  - webapp.demo.watch.momenton.com.au
  resources:
  - annotationwatchlists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.demo.watch.momenton.com.au
  resources:
  - annotationwatchlists/status
  verbs:
  - get
