
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.demo.watch.momenton.com.au
  resources:
  - annotationwatchlists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.demo.watch.momenton.com.au
  resources:
  - annotationwatchlists/status
  verbs:
  - get
  - patch
  - update
