apiVersion: v1
kind: Pod
metadata:
  name: custom-private-pod
  labels:
    app: custom
  annotations:
    oncallPager: 111-222-3333
    imageregistry: "https://hub.docker.com"
    kbArticle: "https://kb.docs.example.com/KB34234"
    "challenge.momenton.com.au/momenton": "false"
spec:
  containers:
  - name: custom-container
    image: mctouch/feature_analysis:latest
    command: ['python3', 'feature_analysis.py']
  restartPolicy: Never
